name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: Build and push the image
       run: |
         docker login --username mcejalvo --password ${{ secrets.GH_PAT }} ghcr.io
         docker build . --tag ghcr.io/mcejalvo/discord-search:latest
         docker push ghcr.io/mcejalvo/discord-search:latest
